// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $author_new from "./routes/author/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $quote_id_ from "./routes/quote/[id].tsx";
import * as $quote_middleware from "./routes/quote/_middleware.tsx";
import * as $quote_delete_id_ from "./routes/quote/delete/[id].tsx";
import * as $quote_newOrEdit from "./routes/quote/newOrEdit.tsx";
import * as $signin from "./routes/signin.tsx";
import * as $signout from "./routes/signout.tsx";
import * as $source_delete_id_ from "./routes/source/delete/[id].tsx";
import * as $source_newOrEdit from "./routes/source/newOrEdit.tsx";
import * as $sources from "./routes/sources.tsx";
import * as $AuthorSourceSelector from "./islands/AuthorSourceSelector.tsx";
import * as $LastSentTime from "./islands/LastSentTime.tsx";
import * as $NewOrEditQuote from "./islands/NewOrEditQuote.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/author/new.tsx": $author_new,
    "./routes/index.tsx": $index,
    "./routes/quote/[id].tsx": $quote_id_,
    "./routes/quote/_middleware.tsx": $quote_middleware,
    "./routes/quote/delete/[id].tsx": $quote_delete_id_,
    "./routes/quote/newOrEdit.tsx": $quote_newOrEdit,
    "./routes/signin.tsx": $signin,
    "./routes/signout.tsx": $signout,
    "./routes/source/delete/[id].tsx": $source_delete_id_,
    "./routes/source/newOrEdit.tsx": $source_newOrEdit,
    "./routes/sources.tsx": $sources,
  },
  islands: {
    "./islands/AuthorSourceSelector.tsx": $AuthorSourceSelector,
    "./islands/LastSentTime.tsx": $LastSentTime,
    "./islands/NewOrEditQuote.tsx": $NewOrEditQuote,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
